[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
price_lock = "BPVWMMj1eEALBvsR3TQZC2Zb3vt8jQkvzBYeJsoaKum7"

[programs.devnet]
price_lock = "BPVWMMj1eEALBvsR3TQZC2Zb3vt8jQkvzBYeJsoaKum7"

[programs.mainnet]
price_lock = "BPVWMMj1eEALBvsR3TQZC2Zb3vt8jQkvzBYeJsoaKum7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
